name: "Make state repos' dispatches"
description: 'Dispatch image changes on multiple state repos'
author: 'Prefapp'

# Define your inputs here.
inputs:
  dispatches_file:
    description: 'Path to the make_dispatches.yaml file of your repo'
    required: true
    default: '.github/make_dispatches.yaml'
  token:
    description: Github token
    required: false
    default: ${{ github.token }}
  dispatch_type:
    description: Dispatch types (releases, snapshots, *)
    required: false
    default: '*'
  flavors:
    description: Flavors to dispatch separated by comma
    required: false
    default: default
  state_repo:
    description:
      List of state repos to dispatch separated by comma (use "*" to target all
      flavors)
    required: false
    default: '*'
  default_registry:
    description: Default registry to use
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
