name: "Make state repos' dispatches"
description: 'Dispatch image changes on multiple state repos'
author: 'Prefapp'

# Define your inputs here.
inputs:
  dispatches_file:
    description: 'Path to the make_dispatches.yaml file of your repo'
    required: true
    default: '.github/make_dispatches.yaml'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
