name: "Make state repos' dispatches"
description: 'Dispatch image changes on multiple state repos'
author: 'Prefapp'

# Define your inputs here.
inputs:
  dispatches_file:
    description: 'Path to the make_dispatches.yaml file of your repo'
    required: true
    default: '.github/make_dispatches.yaml'
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}
  image_type:
    description:
      Image types to filter in the dispatches file (releases, snapshots, *).
      Default to all (*)
    required: false
    default: '*'
  flavors:
    description:
      Filter dispatches by flavor, can be multiple values separated by commas.
    required: false
    default: default
  state_repo:
    description:
      Filter dispatches by state repo, can be multiple values separated by
      commas (use "*" to target all state repos listed in the corresponding
      dispatches section)
    required: false
    default: '*'
  filter_by_env:
    description:
      Dispatch only to state repos whose environment is included in this filter,
      if specified. Can be a comma separated list of environments or * (all)
    required: true
    default: '*'
  filter_by_tenant:
    description:
      Dispatch only to state repos whose tenant is included in this filter, if
      specified. Can be a comma separated list of tenants or * (all)
    required: true
    default: '*'
  overwrite_version:
    description:
      Dispatch using this version instead of the one defined in the dispatches
      file (can be a short-sha or a release tag)
    required: false
    default: ''
  overwrite_tenant:
    description:
      Dispatch using this tenant instead of using the one defined in the
      dispatches file, related to the flavor to deploy.
    required: false
    default: ''
  overwrite_env:
    description:
      Dispatch using this environment instead of using the one defined in the
      dispatches file, related to the flavor to deploy.
    required: false
    default: ''
  registry_base_paths:
    description:
      JSON file specifying the base path of the registry for each kind of
      artifact (service, chart...) and artifact type (release or snapshot)
    required: false
    default: ''
  default_releases_registry:
    description: Default registry to use when dispatching releases
    required: false
  default_snapshots_registry:
    description: Default registry to use when dispatching snapshots
    required: false
  reviewers:
    description:
      List of reviewers' login username, separated by commas, to include in the
      state repo pull request.
    required: false
    default: ''
  build_summary:
    description: Build summary of the last call to build_images.yaml
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
